from pathlib import Path
from io import StringIO
from models import Svg, ChildElement
import xml.etree.ElementTree as ET
from utils import toPascalCase, toHumanReadableLabel

DEFAULT_INDENT_BY = 4

SVG_NAMESPACE = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NAMESPACE)


def gen_indent(level: int) -> str:
    return " " * (DEFAULT_INDENT_BY * level)


def generate_index_file(component_names: list[str]) -> str:
    component_names.sort()

    buffer = StringIO()

    for name in component_names:
        buffer.write(f"export * from './{name}';\n")

    content = buffer.getvalue()
    buffer.close()
    return content


def parse_svg(file_path: Path) -> Svg:
    name = toPascalCase(file_path.stem)
    tree = ET.parse(file_path)
    root = tree.getroot()
    elements: list[ChildElement] = []

    for e in root:
        tag = e.tag.split("}")[1]

        for attr in list(e.attrib):
            if attr == "stroke":
                e.attrib[attr] = "currentColor"
            elif attr == "fill" and e.attrib[attr] != "none":
                e.attrib[attr] = "currentColor"

        elements.append(ChildElement(tag=tag, attrib=e.attrib))

    return Svg(
        name=f"Icon{name}",
        attrib=root.attrib,
        elements=elements,
    )


def build_tsx_component(svg: Svg, header: str | None) -> str:
    buffer = StringIO()

    buffer.write(
        "// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)\n"
    )
    buffer.write("\n")

    if header:
        buffer.write(header.strip())
        buffer.write("\n")

    buffer.write(
        "/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */\n"
    )
    buffer.write("\n")

    buffer.write("import type { JSX } from 'solid-js';\n")
    buffer.write("\n")
    buffer.write(
        f"export const {svg.name} = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {{\n"
    )

    buffer.write(gen_indent(1))
    buffer.write("return (\n")

    buffer.write(gen_indent(2))
    buffer.write("<svg\n")

    buffer.write(gen_indent(3))
    buffer.write("role='img'\n")

    buffer.write(gen_indent(3))
    buffer.write(f"aria-label='{toHumanReadableLabel(svg.name)}'\n")

    for attr in svg.attrib:
        buffer.write(gen_indent(3))
        buffer.write(f"{attr}='{svg.attrib[attr]}'\n")

    buffer.write(gen_indent(3))
    buffer.write("{...props}\n")

    buffer.write(gen_indent(2))
    buffer.write(">\n")

    for element in svg.elements:
        buffer.write(gen_indent(3))
        buffer.write(f"<{element.tag}\n")
        for attr in element.attrib:
            buffer.write(gen_indent(4))
            buffer.write(f"{attr}='{element.attrib[attr]}'\n")
        buffer.write(gen_indent(3))
        buffer.write("/>\n")

    buffer.write(gen_indent(2))
    buffer.write("</svg>\n")

    buffer.write(gen_indent(1))
    buffer.write(");\n")

    buffer.write("};\n")

    content = buffer.getvalue()
    buffer.close()
    return content
